# Generated by Django 3.1.1 on 2020-09-27 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gamemaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats',
                                    to='gamemaster.room'),
        ),
    ]
