# Generated by Django 3.1.2 on 2020-10-09 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nlheroom',
            options={'verbose_name': "No-Limit Texas Hold'em Room"},
        ),
    ]
