# Generated by Django 3.1.1 on 2020-09-29 05:34

import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gamemaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default='Online', max_length=100,
                                                 no_check_for_status=True, null=True),
        ),
    ]
