# Generated by Django 3.1.5 on 2021-01-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='_seats',
            new_name='seats',
        ),
    ]
