# Generated by Django 3.1.2 on 2020-10-09 01:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nlhestat',
            old_name='payoff_sum',
            new_name='payoffs',
        ),
    ]
