# Generated by Django 3.1.2 on 2020-10-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('community', '0002_auto_20201008_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlhestat',
            name='losses',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nlhestat',
            name='ties',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nlhestat',
            name='wins',
            field=models.BigIntegerField(default=0),
        ),
    ]
