# Generated by Django 3.1.2 on 2020-10-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_correspondence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='portfolio',
            new_name='important',
        ),
    ]
